/**
 * Handlers that read the student's project on the control node.
 *
 * These answer structural questions — does the file exist, does it parse, does
 * it contain a task that uses `template`, does the role have the layout roles
 * are supposed to have. They never look at what the student typed, only at what
 * they left behind, so a project written in vim, generated by a script, or
 * pasted in wholesale all grade identically.
 */
import type { RequirementOf } from '@jumptotech/lab-orchestrator';
import type { AnsibleVerifierHandler, HandlerOutcome } from '../contract.js';
import { fail, pass } from '../contract.js';
import type { AnsibleVerifyReader } from '../ansible-reader.js';
import {
  flattenTasks,
  handlerNames,
  moduleMatches,
  nameContains,
  namesMatch,
  parseYamlText,
  playbookHandlers,
  playbookRoles,
  playbookTasks,
  taskHasLoop,
  taskHasWhen,
  taskModule,
  taskName,
  taskNotifies,
  type AnsibleTask,
} from '../ansible-yaml.js';

/*
 * `file_exists` is deliberately NOT handled here.
 *
 * An Ansible lab's project files live on the control node, which the provider
 * exposes through `readSandboxPath` like any other container sandbox — so the
 * existing `filesystem` family already answers them, and the Ansible provider
 * claims that family in `PROVIDER_REQUIREMENT_FAMILIES`. Keeping a second
 * implementation here would mean two `file_exists` checks with two definitions
 * of "exists", which is exactly the drift the family model exists to prevent.
 */

/*
 * `yaml_valid` is deliberately NOT handled here.
 *
 * "Does this file parse as YAML" is the same question for an Ansible playbook
 * and a GitHub Actions workflow, so it belongs to the `filesystem` family that
 * every sandbox provider can answer — see handlers/filesystem.ts. It lived
 * here while Ansible was the only track that asked it, which is exactly how a
 * generic check ends up owned by whichever track happened to need it first.
 */

export const ansiblePlaybookValid: AnsibleVerifierHandler<'ansible_playbook_valid'> = {
  type: 'ansible_playbook_valid',
  label: (r) => `${r.playbook} passes ansible-playbook --syntax-check`,
  async run(requirement, reader) {
    const info = await reader.workspacePath(requirement.playbook);
    if (!info.exists) return fail(`'${requirement.playbook}' does not exist in the lab project`);

    const result = await reader.syntaxCheck(requirement.playbook);
    if (result.timedOut) return fail('the syntax check timed out');
    if (result.exitCode !== 0) {
      return fail(`ansible-playbook rejected the playbook: ${condense(result.stderr || result.stdout)}`);
    }
    return pass();
  },
};

export const ansibleTaskExists: AnsibleVerifierHandler<'ansible_task_exists'> = {
  type: 'ansible_task_exists',
  label: (r) =>
    r.name
      ? `${r.playbook} contains a task named '${r.name}'`
      : `${r.playbook} contains a ${r.module} task`,
  async run(requirement, reader) {
    const parsed = await reader.yaml(requirement.playbook);
    if (parsed === null) return fail(`'${requirement.playbook}' does not exist in the lab project`);
    if (!parsed.ok) return fail(`'${requirement.playbook}' is not valid YAML: ${parsed.error}`);

    const tasks = playbookTasks(parsed.value);
    if (tasks.length === 0) return fail(`'${requirement.playbook}' declares no tasks`);

    const matches = tasks.filter((task) => matchesTask(task, requirement));
    if (matches.length > 0) return pass();

    return fail(describeTaskMiss(tasks, requirement));
  },
};

function matchesTask(task: AnsibleTask, requirement: RequirementOf<'ansible_task_exists'>): boolean {
  if (requirement.module && !moduleMatches(taskModule(task), requirement.module)) return false;
  if (requirement.name && !nameContains(task, requirement.name)) return false;
  if (requirement.has_when === true && !taskHasWhen(task)) return false;
  if (requirement.has_loop === true && !taskHasLoop(task)) return false;
  if (requirement.notifies) {
    const notified = taskNotifies(task);
    if (!notified.some((entry) => namesMatch(entry, requirement.notifies!))) return false;
  }
  return true;
}

/**
 * Explain the miss without giving away the answer.
 *
 * The message says which of the stated conditions the closest task failed, and
 * never what to write — a troubleshooting lab in particular must not have its
 * fault named by the check that grades it.
 */
function describeTaskMiss(
  tasks: AnsibleTask[],
  requirement: RequirementOf<'ansible_task_exists'>,
): string {
  if (requirement.module) {
    const sameModule = tasks.filter((task) => moduleMatches(taskModule(task), requirement.module!));
    if (sameModule.length === 0) {
      return `no task in the playbook uses the ${requirement.module} module`;
    }
    if (requirement.name && !sameModule.some((task) => nameContains(task, requirement.name!))) {
      return `a ${requirement.module} task exists but none is named '${requirement.name}'`;
    }
    if (requirement.has_when === true && !sameModule.some(taskHasWhen)) {
      return `the ${requirement.module} task runs unconditionally — no 'when' condition is set`;
    }
    if (requirement.has_loop === true && !sameModule.some(taskHasLoop)) {
      return `the ${requirement.module} task does not loop over anything`;
    }
    if (requirement.notifies) {
      return `the ${requirement.module} task does not notify '${requirement.notifies}'`;
    }
  }
  if (requirement.name) return `no task is named '${requirement.name}'`;
  return 'no task matches what this check is looking for';
}

export const ansibleRoleExists: AnsibleVerifierHandler<'ansible_role_exists'> = {
  type: 'ansible_role_exists',
  label: (r) => `Role ${r.role} exists with a ${r.requires.join(', ')} directory`,
  async run(requirement, reader) {
    const base = `${requirement.roles_dir}/${requirement.role}`;
    const info = await reader.workspacePath(base);
    if (!info.exists) return fail(`there is no role directory at '${base}'`);
    if (info.kind !== 'directory') return fail(`'${base}' exists but is not a directory`);

    const missing: string[] = [];
    for (const part of requirement.requires) {
      const dir = await reader.workspacePath(`${base}/${part}`);
      if (!dir.exists || dir.kind !== 'directory') {
        missing.push(`${part}/`);
        continue;
      }
      // `templates/` and `files/` hold arbitrary names; the rest are entered
      // through main.yml, which is the file Ansible actually loads.
      if (part === 'templates' || part === 'files') continue;
      const main = await reader.workspacePath(`${base}/${part}/main.yml`);
      const mainYaml = await reader.workspacePath(`${base}/${part}/main.yaml`);
      if (!main.exists && !mainYaml.exists) missing.push(`${part}/main.yml`);
    }

    if (missing.length > 0) {
      return fail(`role '${requirement.role}' is missing: ${missing.join(', ')}`);
    }

    if (requirement.used_by) {
      const parsed = await reader.yaml(requirement.used_by);
      if (parsed === null) return fail(`'${requirement.used_by}' does not exist in the lab project`);
      if (!parsed.ok) return fail(`'${requirement.used_by}' is not valid YAML: ${parsed.error}`);

      const applied = playbookRoles(parsed.value);
      if (!applied.includes(requirement.role)) {
        return fail(
          applied.length > 0
            ? `'${requirement.used_by}' applies ${applied.join(', ')}, not '${requirement.role}'`
            : `'${requirement.used_by}' does not apply any role`,
        );
      }
    }
    return pass();
  },
};

export const ansibleHandlerExists: AnsibleVerifierHandler<'ansible_handler_exists'> = {
  type: 'ansible_handler_exists',
  label: (r) =>
    r.notified
      ? `A handler named '${r.name}' exists and is notified by a task`
      : `A handler named '${r.name}' exists`,
  async run(requirement, reader) {
    const sources = await collectHandlerSources(requirement, reader);
    if (sources.error) return fail(sources.error);

    const found = sources.handlers.some((handler) =>
      handlerNames(handler).some((name) => namesMatch(name, requirement.name)),
    );
    if (!found) {
      const declared = sources.handlers.map(taskName).filter(Boolean);
      return fail(
        declared.length > 0
          ? `no handler named '${requirement.name}' (handlers found: ${declared.join(', ')})`
          : `no handlers are declared where this check looked`,
      );
    }

    if (!requirement.notified) return pass();

    const notified = sources.tasks.some((task) =>
      taskNotifies(task).some((entry) => namesMatch(entry, requirement.name)),
    );
    return notified
      ? pass()
      : fail(`the handler '${requirement.name}' exists but no task notifies it, so it never runs`);
  },
};

/**
 * Gather the handlers and tasks a handler check should look at.
 *
 * A handler may live in a playbook's `handlers:` section or in a role's
 * `handlers/main.yml`, and the task that notifies it may be in either place, so
 * both are collected before matching. A lab naming both looks in both.
 */
async function collectHandlerSources(
  requirement: RequirementOf<'ansible_handler_exists'>,
  reader: AnsibleVerifyReader,
): Promise<{ handlers: AnsibleTask[]; tasks: AnsibleTask[]; error?: string }> {
  const handlers: AnsibleTask[] = [];
  const tasks: AnsibleTask[] = [];

  if (requirement.playbook) {
    const parsed = await reader.yaml(requirement.playbook);
    if (parsed === null) {
      return { handlers, tasks, error: `'${requirement.playbook}' does not exist in the lab project` };
    }
    if (!parsed.ok) {
      return { handlers, tasks, error: `'${requirement.playbook}' is not valid YAML: ${parsed.error}` };
    }
    handlers.push(...playbookHandlers(parsed.value));
    tasks.push(...playbookTasks(parsed.value));
  }

  if (requirement.role) {
    const base = `${requirement.roles_dir}/${requirement.role}`;
    const handlerText = await readMain(reader, `${base}/handlers`);
    if (handlerText.error) return { handlers, tasks, error: handlerText.error };
    if (handlerText.value !== undefined) handlers.push(...flattenTasks(handlerText.value));

    const taskText = await readMain(reader, `${base}/tasks`);
    if (taskText.value !== undefined) tasks.push(...flattenTasks(taskText.value));
  }

  return { handlers, tasks };
}

/** Read a role directory's `main.yml` (or `main.yaml`). */
async function readMain(
  reader: AnsibleVerifyReader,
  directory: string,
): Promise<{ value?: unknown; error?: string }> {
  for (const name of ['main.yml', 'main.yaml']) {
    const text = await reader.workspaceFile(`${directory}/${name}`);
    if (text === null) continue;
    const parsed = parseYamlText(text);
    if (!parsed.ok) return { error: `'${directory}/${name}' is not valid YAML: ${parsed.error}` };
    return { value: parsed.value };
  }
  return {};
}

export const ansibleTemplateExists: AnsibleVerifierHandler<'ansible_template_exists'> = {
  type: 'ansible_template_exists',
  label: (r) => `Template ${r.path} exists and uses Jinja2`,
  async run(requirement, reader) {
    const text = await reader.workspaceFile(requirement.path);
    if (text === null) return fail(`'${requirement.path}' does not exist in the lab project`);
    if (text.trim().length === 0) return fail(`'${requirement.path}' is empty`);

    // A template that interpolates nothing is a copy, not a template — which is
    // precisely the misunderstanding a templates lab exists to correct.
    if (!/\{\{[^}]*\}\}|\{%[^%]*%\}/.test(text)) {
      return fail(`'${requirement.path}' contains no Jinja2 expressions`);
    }

    const missing = requirement.references.filter((name) => !referencesVariable(text, name));
    if (missing.length > 0) {
      return fail(`'${requirement.path}' never uses: ${missing.join(', ')}`);
    }
    return pass();
  },
};

/** Is `name` used inside a Jinja2 expression or statement in this template? */
function referencesVariable(text: string, name: string): boolean {
  const expressions = text.match(/\{\{[^}]*\}\}|\{%[^%]*%\}/g) ?? [];
  const word = new RegExp(`\\b${escapeRegex(name)}\\b`);
  return expressions.some((expression) => word.test(expression));
}

/** Escape a lab-supplied variable name before it becomes part of a pattern. */
function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** Trim a tool's multi-line complaint down to something a student can read. */
function condense(text: string): string {
  const line = text
    .split('\n')
    .map((entry) => entry.trim())
    .find((entry) => entry.length > 0 && !/^\[WARNING\]/i.test(entry));
  return (line ?? 'no output').slice(0, 300);
}

export const ansibleProjectHandlers = {
  ansiblePlaybookValid,
  ansibleTaskExists,
  ansibleRoleExists,
  ansibleHandlerExists,
  ansibleTemplateExists,
} as const;

export type { HandlerOutcome };
