/**
 * Lab verifier.
 *
 * Reads the *desired state* from the lab definition and the *actual state* from
 * the session's sandbox, then reports each requirement independently.
 *
 * A session's sandbox is either a Kubernetes namespace, a workspace directory,
 * or (in principle) both; the requirement type decides which evidence it needs
 * and the reader supplies it. Nothing in this file branches on track or lab.
 *
 * Explicit non-goals:
 *   - It never looks at command history, shell buffers, or terminal output. A
 *     student who creates the Deployment from a manifest, from `kubectl create`,
 *     or from a script they wrote themselves all pass identically, because all
 *     three produce the same desired state. The same is true of a workflow file
 *     written in vi, with a heredoc, or generated by a script.
 *   - It never reveals the solution. Failure details describe *what is wrong
 *     with the observed state*, not what to type.
 *   - It never runs anything the lab author wrote. Requirements select from a
 *     closed vocabulary of handlers that ship with the platform, and the three
 *     handlers that execute anything run a fixed argv from
 *     `workspace/tasks.ts` — never a command line from lab.yaml.
 *
 * Verification is always scoped to one session, which is supplied by the caller
 * from the session record — never by the browser.
 */
import {
  KubernetesUnreachableError,
  type KubernetesPort,
  type LabDefinition,
  type Requirement,
  type WorkspacePort,
} from '@jumptotech/lab-orchestrator';
import { EvidenceUnavailableError, VerifyReader } from './reader.js';
import { checkId, verifyRequirements } from './registry.js';
import type { CheckResult } from './contract.js';

export * from './contract.js';
export * from './registry.js';
export { VerifyReader, EvidenceUnavailableError, type VerifyReaderOptions } from './reader.js';
export { imageMatches, normalizeImageReference } from './image.js';
export { parseQuantity, quantitiesEqual } from './quantity.js';
export * from './ci/workflow.js';
export * from './ci/jenkinsfile.js';
export * from './ci/secrets.js';

export interface VerificationResult {
  labId: string;
  namespace: string;
  passed: boolean;
  /** `LAB PASSED` / `LAB NOT COMPLETE` — the headline the UI renders. */
  summary: 'LAB PASSED' | 'LAB NOT COMPLETE';
  checks: CheckResult[];
  checkedAt: string;
  /** Set when verification could not run at all (sandbox unreachable). */
  error?: { code: string; message: string };
}

export interface VerifyOptions {
  /** Present for Kubernetes-backed sessions. */
  k8s?: KubernetesPort | undefined;
  /** Present for file-backed sessions. */
  workspace?: WorkspacePort | undefined;
  lab: LabDefinition;
  /** The session's isolation identifier — a namespace or a workspace name. */
  namespace: string;
  now?: () => Date;
}

/** Failures that mean "the environment is broken", not "the student is wrong". */
function environmentFailure(error: unknown): { code: string; message: string } | null {
  if (error instanceof KubernetesUnreachableError) {
    return { code: 'ENVIRONMENT_UNREACHABLE', message: error.message };
  }
  if (error instanceof EvidenceUnavailableError) {
    return { code: error.code, message: error.message };
  }
  return null;
}

export async function verifyLab(options: VerifyOptions): Promise<VerificationResult> {
  const { lab, namespace } = options;
  const checkedAt = (options.now?.() ?? new Date()).toISOString();
  const reader = new VerifyReader({
    k8s: options.k8s,
    workspace: options.workspace,
    namespace,
  });

  let checks: CheckResult[];
  try {
    checks = await verifyRequirements(lab.requirements as readonly Requirement[], reader);
  } catch (error) {
    // A sandbox we cannot read is not a failed lab — it is a broken
    // environment, and the UI must say so rather than blame the student.
    const failure = environmentFailure(error);
    if (failure) {
      return {
        labId: lab.id,
        namespace,
        passed: false,
        summary: 'LAB NOT COMPLETE',
        checkedAt,
        checks: (lab.requirements as readonly Requirement[]).map((requirement, index) => ({
          id: checkId(requirement, index),
          label: requirement.label ?? requirement.type,
          status: 'skipped' as const,
          detail: 'Could not read the lab environment',
        })),
        error: failure,
      };
    }
    throw error;
  }

  const passed = checks.length > 0 && checks.every((c) => c.status === 'pass');
  return {
    labId: lab.id,
    namespace,
    passed,
    summary: passed ? 'LAB PASSED' : 'LAB NOT COMPLETE',
    checks,
    checkedAt,
  };
}

/**
 * Poll a set of requirements until they all pass or the deadline expires.
 *
 * Used for lab *setup* verification: after the initial state is applied, the
 * Deployment it created needs a moment to become available, and a seeded
 * workspace needs its files to be on disk. A student must never be handed an
 * environment whose starting condition was never confirmed, so provisioning
 * waits here rather than hoping.
 */
export async function waitForRequirements(options: {
  k8s?: KubernetesPort | undefined;
  workspace?: WorkspacePort | undefined;
  namespace: string;
  requirements: readonly Requirement[];
  timeoutMs: number;
  intervalMs?: number;
  now?: () => number;
  sleep?: (ms: number) => Promise<void>;
}): Promise<{ ok: boolean; checks: CheckResult[] }> {
  const now = options.now ?? (() => Date.now());
  const sleep = options.sleep ?? ((ms: number) => new Promise<void>((r) => setTimeout(r, ms)));
  const intervalMs = options.intervalMs ?? 1_000;
  const deadline = now() + options.timeoutMs;

  if (options.requirements.length === 0) return { ok: true, checks: [] };

  let checks: CheckResult[] = [];
  for (;;) {
    // A fresh reader each round: the cache must not outlive one observation.
    checks = await verifyRequirements(
      options.requirements,
      new VerifyReader({
        k8s: options.k8s,
        workspace: options.workspace,
        namespace: options.namespace,
      }),
    );
    if (checks.every((c) => c.status === 'pass')) return { ok: true, checks };
    if (now() >= deadline) return { ok: false, checks };
    await sleep(intervalMs);
  }
}
