#!/bin/bash
# ---------------------------------------------------------------------------
# LINUX-016 baseline — three sweeps over one host, each with something nearby
# that must survive it.
#
# The lab is about scope. Every one of the three tasks has an obvious wide
# version that produces the right result for the thing you were looking at and
# damages something you were not:
#
#   substitution   a sed across /srv/jumptotech rewrites the change log in
#                  archive/ that records what the old hostname used to be
#   aggregation    a sum that forgets `status=settled` counts reversed
#                  payments as revenue
#   cleanup        a `rm *.tmp` takes this morning's spool files and silently
#                  misses the hidden one, because the shell's glob skips names
#                  beginning with a dot while find's -name does not
#
# So the graded state includes the survivors, not only the casualties. That is
# the whole difference between a sweep and an accident.
#
# THE PAYMENTS DATA IS GENERATED, NOT SHIPPED
#
# 2000 lines from a Lehmer generator with a fixed seed, so the file is
# byte-identical on every run and the expected totals can be literals in
# lab.yaml. The multiplier is 16807 and the modulus 2147483647, which keeps
# every intermediate product under 2^53 and therefore exact in awk's doubles —
# a larger multiplier would silently lose precision and make the data
# non-reproducible.
#
# The volume is deliberate. Eight merchants over two thousand transactions is
# not something a student can total by hand, so the only practical route to the
# answer is to actually aggregate the file.
#
# Content is written from the GNU sed, GNU awk and GNU findutils manuals only.
# ---------------------------------------------------------------------------
set -euo pipefail

CONF=/srv/jumptotech/conf
SPOOL=/srv/jumptotech/spool
ARCHIVE=/srv/jumptotech/archive
LOGS=/var/log/jumptotech

OLD_HOST=ledger-old.jumptotech.internal

install -d -o student -g student -m 0755 /srv/jumptotech
install -d -o student -g student -m 0755 "${CONF}" "${CONF}/services" "${CONF}/edge"
install -d -o student -g student -m 0755 "${SPOOL}" "${ARCHIVE}"
install -d -o root -g root -m 0755 "${LOGS}"
install -d -o student -g student -m 0755 /home/student/analysis

# --- 1. the config tree ------------------------------------------------------
#
# Owned by the student: this lab needs no elevated privilege anywhere, and a
# bulk edit is exactly the operation where running as root by reflex is how
# people damage a host.
mk_conf() {
  local path="$1" svc="$2"
  cat > "${path}" <<EOF
# ${svc} — deployment configuration
upstream_host = ${OLD_HOST}
upstream_port = 9105
service_name  = ${svc}
retry_backoff = 250ms
health_path   = /healthz
EOF
}

for svc in ledger payments clearing settlement reconciliation \
           notifications audit reporting exports webhooks; do
  mk_conf "${CONF}/services/${svc}.conf" "${svc}"
done
for svc in edge-north edge-south edge-east edge-west \
           edge-cache edge-tls edge-waf edge-lb; do
  mk_conf "${CONF}/edge/${svc}.conf" "${svc}"
done
mk_conf "${CONF}/defaults.conf" defaults
mk_conf "${CONF}/site.conf" site

# Not a .conf, and it must keep the old name: it is prose describing history,
# not configuration. A sweep that matches on directory rather than on filename
# rewrites it.
cat > "${CONF}/README.txt" <<EOF
Configuration tree for the JumpToTech Bank platform.

Every service in services/ and edge/ points at the shared ledger front end.
Until the migration this was ${OLD_HOST}; see ../archive/ for the change
record. Do not edit this file when retargeting services — it documents what
the estate used to look like, and the auditors read it.
EOF

# Outside the config tree entirely, and likewise must keep the old name.
cat > "${ARCHIVE}/2026-06-change-record.log" <<EOF
2026-06-02 CHG-1188 approved: retire ${OLD_HOST} after the ledger migration
2026-06-14 CHG-1188 scheduled for the August maintenance window
2026-08-01 CHG-1188 migration window opened; ${OLD_HOST} to be replaced
EOF

# --- 2. the payments log -----------------------------------------------------
awk '
BEGIN {
  n = split("acme-retail,bolt-foods,cinder-media,delta-travel,ember-books,forge-tools,gale-energy,harbor-freight", M, ",")
  seed = 20260801
  for (i = 1; i <= 2000; i++) {
    seed = (seed * 16807) % 2147483647; m   = M[(seed % n) + 1]
    seed = (seed * 16807) % 2147483647; amt = 50 + (seed % 901)
    seed = (seed * 16807) % 2147483647; st  = (seed % 5 == 0) ? "reversed" : "settled"
    seed = (seed * 16807) % 2147483647; day = 1 + (seed % 20)
    printf "2026-08-%02d 0%d:%02d:%02d TXN-%05d merchant=%s amount=%d status=%s\n", \
      day, (i%9)+1, i%60, (i*7)%60, 10000+i, m, amt, st
  }
}' > "${LOGS}/payments-2026-08.log"
chmod 0644 "${LOGS}/payments-2026-08.log"

# --- 3. the spool ------------------------------------------------------------
#
# Backdated well past the seven-day line rather than near it: `-mtime +7`
# excludes a file exactly seven days old, and a lab should not hinge on which
# side of a rounding boundary a student lands.
stale() { : > "$1"; touch -d '30 days ago' "$1"; }
fresh() { : > "$1"; touch -d '1 day ago'  "$1"; }

stale "${SPOOL}/export-2026-07-04.tmp"
stale "${SPOOL}/export-2026-07-11.tmp"
stale "${SPOOL}/reconcile-2026-07-18.tmp"
# A hidden stale export. The shell's `*.tmp` glob does not match names that
# begin with a dot, so `rm *.tmp` silently leaves this one behind; find's
# -name matches on the whole basename and picks it up. That difference is the
# lesson, and it is why this lab grades the sweep rather than the command.
stale "${SPOOL}/.export-2026-07-25.tmp"

# This morning's work. Still needed.
fresh "${SPOOL}/export-2026-08-24.tmp"
fresh "${SPOOL}/export-2026-08-25.tmp"

# Old, but not a .tmp — the retention rule is about temporary exports, and this
# is the spool's own history. A sweep matching on age alone removes it.
stale "${SPOOL}/spool-history.log"

chown -R student:student /srv/jumptotech
