#!/usr/bin/env bash
#
# Browser E2E stack lifecycle — TEST ONLY.
#
#   bash e2e/stack.sh up       build and start the stack, then wait until it is usable
#   bash e2e/stack.sh wait     readiness gate only (fails closed, bounded)
#   bash e2e/stack.sh status   compose ps for the E2E project
#   bash e2e/stack.sh logs     recent logs of every E2E service (diagnostics)
#   bash e2e/stack.sh config   resolve the merged compose model; starts nothing
#   bash e2e/stack.sh down     stop, delete volumes, remove this owner's sandboxes
#   bash e2e/stack.sh service stop|recreate api|terminal
#                              stop one platform service, or re-create it the way
#                              an operator's `up -d <service>` does (new container)
#   bash e2e/stack.sh service restart|stop|start postgres
#                              restart, stop or start the database container; its volume is kept
#   bash e2e/stack.sh run [playwright args…]
#                              up → playwright → down, always tearing down
#                              (E2E_KEEP_STACK=1 leaves it running)
#
# The stack is the real one — docker-compose.yml + docker-compose.runtime.yml —
# plus e2e/docker-compose.e2e.yml, which adds a loopback test identity provider
# and switches the api to OIDC browser sign-in. See
# docs/development/browser-e2e-private-beta.md.
#
# Secrets are generated per stack with openssl into e2e/.stack/stack.env
# (git-ignored, mode 600) and are never printed. The file is deleted by `down`.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STACK_DIR="${REPO_ROOT}/e2e/.stack"
ENV_FILE="${STACK_DIR}/stack.env"

PROJECT="${E2E_PROJECT:-jtt-e2e}"
if [[ ! "${PROJECT}" =~ ^[a-z0-9][a-z0-9-]{0,30}$ ]]; then
  echo "E2E_PROJECT must match ^[a-z0-9][a-z0-9-]{0,30}\$" >&2
  exit 2
fi
OWNER="${PROJECT}"
WEB_PORT="${E2E_WEB_PORT:-33700}"
API_PORT="${E2E_API_PORT:-34700}"
TERMINAL_PORT="${E2E_TERMINAL_PORT:-34701}"
POSTGRES_PORT="${E2E_POSTGRES_PORT:-55700}"
OIDC_PORT="${E2E_OIDC_PORT:-39700}"
LINUX_IMAGE="${E2E_LINUX_SANDBOX_IMAGE:-jumptotech/lab-linux:e2e}"
READY_TIMEOUT_SECONDS="${E2E_READY_TIMEOUT_SECONDS:-300}"

log() { printf '[e2e-stack] %s\n' "$*"; }
die() { printf '[e2e-stack] ERROR: %s\n' "$*" >&2; exit 1; }

# A scrubbed environment: compose lets shell variables override --env-file, so
# an inherited RUNTIME_OWNER_ID (CI sets one per job) or AUTH_MODE would
# silently change the stack this script believes it started.
compose() {
  env -i PATH="${PATH}" HOME="${HOME}" \
    ${DOCKER_HOST:+DOCKER_HOST="${DOCKER_HOST}"} \
    ${DOCKER_CONTEXT:+DOCKER_CONTEXT="${DOCKER_CONTEXT}"} \
    ${DOCKER_CONFIG:+DOCKER_CONFIG="${DOCKER_CONFIG}"} \
  docker compose \
    --project-name "${PROJECT}" \
    --project-directory "${REPO_ROOT}" \
    --env-file "${ENV_FILE}" \
    -f "${REPO_ROOT}/docker-compose.yml" \
    -f "${REPO_ROOT}/docker-compose.runtime.yml" \
    -f "${REPO_ROOT}/e2e/docker-compose.e2e.yml" \
    "$@"
}

project_running() {
  [[ -n "$(docker ps -q --filter "label=com.docker.compose.project=${PROJECT}")" ]]
}

port_in_use() {
  (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null
}

secret() {
  local value
  value="$(openssl rand -hex 32)"
  [[ ${#value} -eq 64 ]] || die "openssl did not produce a 32-byte secret"
  printf '%s' "${value}"
}

write_env() {
  command -v openssl >/dev/null || die "openssl is required"
  mkdir -p "${STACK_DIR}"
  local socket_gid=0
  if [[ "$(uname -s)" == "Linux" && -S /var/run/docker.sock ]]; then
    socket_gid="$(stat -c %g /var/run/docker.sock)"
  fi
  umask 077
  {
    echo "# Generated by e2e/stack.sh for compose project ${PROJECT}. Test-only values. Do not commit."
    echo "COMPOSE_PROJECT_NAME=${PROJECT}"
    echo "RUNTIME_OWNER_ID=${OWNER}"
    echo "DOCKER_SANDBOX_NETWORK=${PROJECT}-sandboxes"
    echo "DOCKER_SOCKET_GID=${socket_gid}"
    echo "WEB_PORT=${WEB_PORT}"
    echo "API_PORT=${API_PORT}"
    echo "TERMINAL_PORT=${TERMINAL_PORT}"
    echo "POSTGRES_PORT=${POSTGRES_PORT}"
    echo "E2E_OIDC_PORT=${OIDC_PORT}"
    echo "E2E_LINUX_SANDBOX_IMAGE=${LINUX_IMAGE}"
    # The private-beta capacity contract, so the five-student spec meets the
    # real ceiling rather than compose's general default of 20.
    echo "MAX_ACTIVE_SESSIONS=5"
    echo "MAX_ACTIVE_SESSIONS_PER_STUDENT=1"
    echo "POSTGRES_PASSWORD=$(secret)"
    echo "TERMINAL_SESSION_SECRET=$(secret)"
    echo "INTERNAL_SERVICE_SECRET=$(secret)"
    echo "NAMESPACE_DERIVATION_SECRET=$(secret)"
    echo "OBSERVABILITY_SCRAPE_TOKEN=$(secret)"
    echo "SANDBOXD_ATTACH_SECRET=$(secret)"
    echo "SANDBOXD_RUNTIME_SECRET=$(secret)"
    echo "SANDBOXD_DOCKER_SECRET=$(secret)"
    echo "E2E_OIDC_CLIENT_SECRET=$(secret)"
  } > "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
}

# Readiness, bounded and fail-closed: every condition the browser tests depend
# on must hold, or this exits non-zero and no test runs.
wait_ready() {
  [[ -f "${ENV_FILE}" ]] || die "no ${ENV_FILE}; run 'bash e2e/stack.sh up' first"
  local deadline=$((SECONDS + READY_TIMEOUT_SECONDS)) last=""
  local web="http://127.0.0.1:${WEB_PORT}"
  while (( SECONDS < deadline )); do
    last="$(node - "${web}" "${API_PORT}" "${OIDC_PORT}" <<'NODE' 2>&1
const [web, apiPort, oidcPort] = process.argv.slice(2);
const get = async (url) => {
  const r = await fetch(url, { signal: AbortSignal.timeout(5000), redirect: 'manual' });
  if (!r.ok) throw new Error(`${url} -> HTTP ${r.status}`);
  return r;
};
(async () => {
  await get(`${web}/`);
  const discovery = await (await get(`http://127.0.0.1:${oidcPort}/.well-known/openid-configuration`)).json();
  if (discovery.issuer !== 'http://oidc:9500') throw new Error('oidc discovery issuer mismatch');
  const auth = await (await get(`${web}/auth/config`)).json();
  const cfg = auth.data ?? auth;
  if (cfg.mode !== 'oidc' || cfg.signInAvailable !== true) throw new Error(`auth not ready: ${JSON.stringify(cfg)}`);
  const health = (await (await get(`http://127.0.0.1:${apiPort}/health`)).json()).data;
  if (!(health.labsLoaded > 0)) throw new Error('api has no labs loaded');
  const linux = (health.providers ?? []).find((p) => p.provider === 'linux');
  if (!linux?.available) throw new Error(`linux provider not available: ${JSON.stringify(linux ?? null)}`);
  console.log(`ready: ${health.labsLoaded} labs, linux provider available, oidc sign-in enabled`);
})().catch((e) => { console.error(e.message); process.exit(1); });
NODE
)" && { log "${last}"; return 0; }
    sleep 3
  done
  log "last readiness failure: ${last}"
  compose ps || true
  die "stack not ready after ${READY_TIMEOUT_SECONDS}s"
}

cmd_up() {
  docker version --format '{{.Server.Version}}' >/dev/null 2>&1 || die "the Docker daemon is not responding"
  if project_running; then
    [[ -f "${ENV_FILE}" ]] || die "project ${PROJECT} is running but ${ENV_FILE} is missing; run 'bash e2e/stack.sh down' first"
    log "project ${PROJECT} already running; reusing it"
  else
    for port in "${WEB_PORT}" "${API_PORT}" "${TERMINAL_PORT}" "${POSTGRES_PORT}" "${OIDC_PORT}"; do
      port_in_use "${port}" && die "127.0.0.1:${port} is already in use; set the E2E_*_PORT variables"
    done
    write_env
  fi

  if [[ "${E2E_REBUILD_SANDBOX:-0}" == "1" ]] || ! docker image inspect "${LINUX_IMAGE}" >/dev/null 2>&1; then
    log "building ${LINUX_IMAGE}"
    docker build --file "${REPO_ROOT}/infrastructure/docker/sandbox-linux.Dockerfile" --tag "${LINUX_IMAGE}" "${REPO_ROOT}"
  fi

  log "starting compose project ${PROJECT} (web http://127.0.0.1:${WEB_PORT})"
  compose up -d --build --wait --wait-timeout "${READY_TIMEOUT_SECONDS}"
  wait_ready
}

cmd_down() {
  if [[ -f "${ENV_FILE}" ]]; then
    compose down --volumes --remove-orphans --timeout 20 || true
  elif project_running; then
    die "project ${PROJECT} is running but ${ENV_FILE} is missing; remove it with docker compose -p ${PROJECT} down -v"
  fi
  RUNTIME_OWNER_ID="${OWNER}" bash "${REPO_ROOT}/scripts/sandbox-clean.sh"
  rm -f "${ENV_FILE}"
  local leaked
  leaked="$(docker ps -aq --filter "label=jumptotech.io/runtime-owner=${OWNER}")"
  [[ -z "${leaked}" ]] || die "sandbox containers for owner ${OWNER} still exist after cleanup"
  log "stack ${PROJECT} removed"
}

cmd_run() {
  local status=0
  if [[ "${E2E_KEEP_STACK:-0}" == "1" ]]; then
    log "E2E_KEEP_STACK=1: the stack will be left running"
  else
    # Tear down on every exit path, including a failed `up`.
    trap 'cmd_down' EXIT
  fi
  cmd_up
  (
    cd "${REPO_ROOT}"
    E2E_BASE_URL="http://127.0.0.1:${WEB_PORT}" \
    E2E_API_URL="http://127.0.0.1:${API_PORT}" \
    E2E_RUNTIME_OWNER_ID="${OWNER}" \
      npx playwright test --config e2e/playwright.config.ts "$@"
  ) || status=$?
  return "${status}"
}

# Used by the failure-path specs to take a real service away mid-session.
cmd_service() {
  local action="${1:-}" service="${2:-}"
  [[ -f "${ENV_FILE}" ]] || die "no ${ENV_FILE}; the stack is not up"
  case "${action}:${service}" in
    stop:api|stop:terminal) compose stop --timeout 10 "${service}" ;;
    recreate:api|recreate:terminal)
      compose up -d --no-deps --force-recreate --wait --wait-timeout "${READY_TIMEOUT_SECONDS}" "${service}" ;;
    # restart, never down/rm: the named volume and its data stay.
    restart:postgres) compose restart --timeout 20 postgres ;;
    # stop/start, never down/rm: the named volume and its data stay.
    stop:postgres) compose stop --timeout 20 postgres ;;
    start:postgres) compose start postgres && compose up -d --no-deps --wait --wait-timeout "${READY_TIMEOUT_SECONDS}" postgres ;;
    *) die "supported: stop|recreate api|terminal, restart|stop|start postgres" ;;
  esac
}

case "${1:-}" in
  up) cmd_up ;;
  wait) wait_ready ;;
  status) compose ps ;;
  logs) compose logs --no-color --tail "${E2E_LOG_TAIL:-200}" ;;
  config)
    # Resolve the merged compose model without starting anything.
    [[ -f "${ENV_FILE}" ]] || write_env
    compose config --quiet && log "compose model resolves" ;;
  down) cmd_down ;;
  service) shift; cmd_service "$@" ;;
  run) shift; cmd_run "$@" ;;
  *) echo "usage: bash e2e/stack.sh up|wait|status|logs|config|down|service stop|recreate api|terminal|restart|stop|start postgres|run [playwright args]" >&2; exit 2 ;;
esac
