/*
 * JumpToTech Bank — build.
 *
 *   node build.mjs
 *
 * Produces the two artifacts a pipeline would publish:
 *
 *   dist/statements.bundle.js   one self-contained file, no imports
 *   dist/build-info.json        what went into it, and a digest of each input
 *
 * Deliberately small and dependency-free. The point of a build step in these
 * labs is that source is not what gets deployed — something is produced from
 * it, and that something is the artifact the rest of the pipeline carries.
 */
import { createHash } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

const OUT_DIR = 'dist';
const SOURCES = ['src/statements.mjs'];
const EXPORTED = ['formatAmount', 'summarise', 'renderStatement', 'CURRENCY_SYMBOLS'];

function sha256(text) {
  return createHash('sha256').update(text).digest('hex').slice(0, 16);
}

async function readPackageVersion() {
  try {
    const raw = await readFile('package.json', 'utf8');
    return JSON.parse(raw).version ?? '0.0.0';
  } catch {
    return '0.0.0';
  }
}

async function main() {
  const version = await readPackageVersion();

  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  const inputs = [];
  const parts = [];

  for (const source of SOURCES) {
    let text;
    try {
      text = await readFile(source, 'utf8');
    } catch {
      throw new Error(`cannot read source file '${source}'`);
    }
    if (text.trim().length === 0) throw new Error(`source file '${source}' is empty`);

    inputs.push({ path: source, bytes: Buffer.byteLength(text), sha256: sha256(text) });
    // The bundle is a single script, so the module keywords come off. This is
    // why src/statements.mjs is written without any imports of its own.
    parts.push(`// --- ${source} ---\n${text.replace(/^export\s+/gm, '')}`);
  }

  const bundle = [
    `// JumpToTech statements ${version} — generated by build.mjs. Do not edit.`,
    "'use strict';",
    '',
    ...parts,
    '',
    `if (typeof module !== 'undefined') { module.exports = { ${EXPORTED.join(', ')} }; }`,
    '',
  ].join('\n');

  const bundlePath = path.join(OUT_DIR, 'statements.bundle.js');
  await writeFile(bundlePath, bundle);

  await writeFile(
    path.join(OUT_DIR, 'build-info.json'),
    `${JSON.stringify(
      {
        name: 'jumptotech-statements',
        version,
        builtAt: new Date().toISOString(),
        artifact: bundlePath,
        bytes: Buffer.byteLength(bundle),
        inputs,
      },
      null,
      2,
    )}\n`,
  );

  console.log(
    `built ${bundlePath} (${Buffer.byteLength(bundle)} bytes) from ${inputs.length} source file(s)`,
  );
}

main().catch((error) => {
  console.error(`build failed: ${error.message}`);
  process.exit(1);
});
