#!/usr/bin/env tsx
/**
 * Certification coverage report and gate.
 *
 *   npm run certification            # every certification the repo defines
 *   npm run certification:terraform  # just the Terraform Associate track
 *
 * Loads the lab registry and the certification registry from `labs/`, computes
 * the coverage matrix, prints it, and exits non-zero when an official objective
 * is not fully covered — or when any lab, study unit, question or exam failed to
 * load. The same computation backs `GET /api/certifications/:id/coverage` and
 * the coverage test, so the number in CI, the number in the API and the number
 * on this terminal cannot disagree.
 *
 * What the percentage means: the share of *published objectives* our curriculum
 * maps onto with the delivery the catalog says each one needs. It is a statement
 * about this repository, not a prediction about anybody's exam result, and the
 * output says so.
 *
 * `--markdown` writes the matrix as a table, which is how
 * docs/certifications/terraform-associate-004-coverage.md is kept honest.
 */
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeFile } from 'node:fs/promises';
import {
  CertificationRegistry,
  LabRegistry,
  coverageViolations,
  type CoverageReport,
  type LoadedLabDefinition,
} from '../services/lab-orchestrator/src/index.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const LABS_DIR = process.env.LABS_DIR ?? path.join(ROOT, 'labs');

interface Options {
  certification?: string;
  track?: string;
  markdownPath?: string;
}

function parseArgs(argv: string[]): Options {
  const options: Options = {};
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]!;
    if (arg === '--certification' || arg === '-c') options.certification = argv[++i];
    else if (arg === '--track' || arg === '-t') options.track = argv[++i];
    else if (arg === '--markdown') options.markdownPath = argv[++i];
    else if (!arg.startsWith('-')) options.certification = arg;
  }
  return options;
}

const BOLD = '[1m';
const DIM = '[2m';
const RED = '[31m';
const GREEN = '[32m';
const YELLOW = '[33m';
const RESET = '[0m';

const colour = process.stdout.isTTY === true && !process.env.NO_COLOR;
const paint = (code: string, text: string): string => (colour ? `${code}${text}${RESET}` : text);

const STATUS_COLOUR = { FULL: GREEN, PARTIAL: YELLOW, MISSING: RED } as const;

function bar(percent: number, width = 24): string {
  const filled = Math.round((percent / 100) * width);
  return `${'█'.repeat(filled)}${'·'.repeat(width - filled)}`;
}

function printReport(report: CoverageReport, labs: readonly LoadedLabDefinition[]): void {
  const trackLabs = labs.filter((lab) =>
    lab.certification.some((entry) => entry.relevant && entry.certification === report.certification),
  );

  console.log('');
  console.log(paint(BOLD, `${report.name}`));
  console.log(
    paint(
      DIM,
      `exam ${report.examVersion} · targets ${report.productVersion} · objective list reviewed ${report.reviewedOn}`,
    ),
  );
  console.log('');

  for (const domain of report.domains) {
    const status = domain.percent === 100 ? GREEN : domain.percent >= 50 ? YELLOW : RED;
    console.log(
      `  ${paint(BOLD, `Domain ${domain.domain}`)} ${domain.title}`.padEnd(colour ? 72 : 64) +
        `${paint(status, bar(domain.percent))} ${String(domain.percent).padStart(3)}%`,
    );
    for (const objective of domain.objectives) {
      const marker = paint(STATUS_COLOUR[objective.status], objective.status.padEnd(7));
      const delivery =
        objective.labs.length > 0 ? objective.labs.join(', ') : objective.studyUnits.join(', ') || '—';
      console.log(
        `      ${objective.objective.padEnd(4)} ${marker} ${paint(DIM, `${objective.practice.padEnd(10)} ${delivery.padEnd(22)} ${objective.questions.length} question${objective.questions.length === 1 ? '' : 's'}`)}`,
      );
      for (const gap of objective.gaps) {
        console.log(`             ${paint(RED, `↳ ${gap}`)}`);
      }
    }
    console.log('');
  }

  console.log(
    `  ${paint(BOLD, 'Overall objective coverage')}  ${paint(report.complete ? GREEN : RED, `${report.percent}%`)}` +
      `  (${report.full} full, ${report.partial} partial, ${report.missing} missing, of ${report.total})`,
  );
  console.log(
    paint(DIM, `  Curriculum: ${trackLabs.length} hands-on labs mapped to this certification`),
  );
  console.log(
    paint(
      DIM,
      '  This measures our coverage of the published objectives. It is not a prediction of exam results.',
    ),
  );
  console.log('');
}

function toMarkdown(report: CoverageReport): string {
  const lines: string[] = [];
  lines.push(`# ${report.name} — coverage matrix`);
  lines.push('');
  lines.push(
    `Generated by \`npm run certification:terraform -- --markdown <file>\`. Do not edit by hand.`,
  );
  lines.push('');
  lines.push(
    `- Exam version: **${report.examVersion}** · targets **Terraform ${report.productVersion}**`,
  );
  lines.push(`- Official objective list reviewed: **${report.reviewedOn}**`);
  lines.push(
    `- Overall objective coverage: **${report.percent}%** (${report.full} full, ${report.partial} partial, ${report.missing} missing, of ${report.total})`,
  );
  lines.push('');
  lines.push(
    'Coverage measures how this curriculum maps onto the published objectives. It is not a prediction of exam results.',
  );
  lines.push('');

  for (const domain of report.domains) {
    lines.push(`## Domain ${domain.domain} — ${domain.title} (${domain.percent}%)`);
    lines.push('');
    lines.push('| Objective | Title | Delivery | Hands-on labs | Study units | Questions | Coverage |');
    lines.push('| --- | --- | --- | --- | --- | --- | --- |');
    for (const objective of domain.objectives) {
      lines.push(
        `| \`${objective.objective}\` | ${objective.title} | ${objective.practice} | ${objective.labs.join(', ') || '—'} | ${objective.studyUnits.join(', ') || '—'} | ${objective.questions.length} | **${objective.status}** |`,
      );
    }
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2));

  const labs = new LabRegistry(LABS_DIR);
  await labs.load();

  const certifications = new CertificationRegistry(LABS_DIR);
  await certifications.load(labs.all());

  let failed = false;

  if (labs.loadErrors.length > 0) {
    failed = true;
    console.error(paint(RED, `\n${labs.loadErrors.length} lab definition(s) failed to load:`));
    for (const error of labs.loadErrors) console.error(`\n${error}`);
  }
  if (certifications.loadErrors.length > 0) {
    failed = true;
    console.error(
      paint(RED, `\n${certifications.loadErrors.length} certification file(s) failed to load:`),
    );
    for (const error of certifications.loadErrors) console.error(`\n${error}`);
  }

  const selected = certifications
    .certifications()
    .filter((catalog) => !options.certification || catalog.id === options.certification)
    .filter((catalog) => !options.track || catalog.track === options.track);

  if (selected.length === 0) {
    console.error(
      paint(
        RED,
        `No certification catalog matched${options.certification ? ` id '${options.certification}'` : ''}${options.track ? ` track '${options.track}'` : ''}.`,
      ),
    );
    process.exitCode = 1;
    return;
  }

  for (const catalog of selected) {
    const report = certifications.coverage(catalog.id, labs.all())!;
    printReport(report, labs.all());

    if (options.markdownPath) {
      const target = path.resolve(ROOT, options.markdownPath);
      await writeFile(target, toMarkdown(report), 'utf8');
      console.log(paint(DIM, `  wrote ${path.relative(ROOT, target)}`));
      console.log('');
    }

    const violations = coverageViolations(report);
    if (violations.length > 0) {
      failed = true;
      console.error(paint(RED, `  ${violations.length} objective(s) are not fully covered:`));
      for (const violation of violations) console.error(paint(RED, `    - ${violation}`));
      console.error('');
    }
  }

  if (failed) {
    console.error(paint(RED, 'Certification coverage gate FAILED.'));
    process.exitCode = 1;
    return;
  }
  console.log(paint(GREEN, 'Certification coverage gate passed.'));
}

main().catch((error: unknown) => {
  console.error('[certification] failed:', error);
  process.exitCode = 1;
});
