/**
 * LINUX-018 — a crontab that reads correctly is not a job that ran.
 *
 * The regression this file guards against is the obvious simplification:
 * grading the crontab and stopping there. The seeded entry is syntactically
 * valid, parses without complaint, and has never produced anything — so a lab
 * that only read the crontab would pass a host where nothing has run in three
 * weeks, which is the exact fault it is supposed to teach.
 *
 * The execution evidence is `RUNBY=`, which the rollup tool derives by walking
 * its own process ancestry through /proc until pid 1 and reporting whether
 * `cron` was among its ancestors. That was confirmed against the real sandbox
 * image: a hand-run reported `RUNBY=shell CHAIN: sh su sh`, a scheduled run
 * `RUNBY=cron CHAIN: sh cron`. What is asserted here is that the *lab* reads
 * that evidence and fails the hosts it ought to.
 */
import { describe, expect, it } from 'vitest';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadLabDefinition } from '@jumptotech/lab-orchestrator';
import { verifyLab } from '../src/index.js';
import { FakeSandbox, type FakeWorld } from './sandbox-fake.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const LAB_YAML = path.resolve(here, '../../../labs/linux/linux-018-cron/lab.yaml');
const SANDBOX = 'jtt-lab-000000000018';

const TOOL = '/usr/local/lib/jumptotech/jtt-rollup';
const STATUS = '/var/lib/jumptotech/rollup/status.txt';
const CRON_LOG = '/var/log/jumptotech/rollup-cron.log';
const READ_CRONTAB = 'cat /var/spool/cron/crontabs/student';
const STATUS_FRESH = `find ${STATUS} -mmin -3`;

/** The entry that satisfies the runbook. */
const CORRECT_ENTRY =
  `* * * * * ${TOOL} >> ${CRON_LOG} 2>&1\n`;
/** What the previous engineer left: daily, bare name, output discarded. */
const SEEDED_ENTRY = '0 3 * * * jtt-rollup\n';

interface WorldOptions {
  crontab?: string;
  toolMode?: string;
  status?: string | null;
  cronLog?: string;
  fresh?: boolean;
  cronRunning?: boolean;
}

function world(o: WorldOptions = {}): FakeWorld {
  const {
    crontab = CORRECT_ENTRY,
    toolMode = '755',
    status = 'ROLLUP=OK\nRUNBY=cron\nRECORDS=1440\nAT=2026-08-25T14:35:02+00:00\n',
    cronLog = 'rollup complete: 1440 records\n',
    fresh = true,
    cronRunning = true,
  } = o;

  const files: NonNullable<FakeWorld['files']> = {
    [TOOL]: { type: 'file', mode: toolMode, owner: 'root', group: 'root', content: '#!/bin/sh\n' },
    [CRON_LOG]: { type: 'file', mode: '644', owner: 'student', group: 'student', content: cronLog },
  };
  if (status !== null) {
    files[STATUS] = { type: 'file', mode: '644', owner: 'student', group: 'student', content: status };
  }

  // A file that does not exist cannot be fresh. Coupling these keeps a world
  // from describing a host that could not occur.
  const reportsFresh = fresh && status !== null;

  return {
    processes: cronRunning
      ? ['    1 root     /usr/bin/runsvdir -P /etc/service', '   88 root     /usr/sbin/cron -f']
      : ['    1 root     /usr/bin/runsvdir -P /etc/service'],
    commands: {
      [READ_CRONTAB]: { exitCode: 0, stdout: `# DO NOT EDIT THIS FILE\n${crontab}` },
      [STATUS_FRESH]: { exitCode: 0, stdout: reportsFresh ? `${STATUS}\n` : '' },
    },
    files,
  };
}

function lab() {
  return loadLabDefinition(LAB_YAML);
}

async function verify(w: FakeWorld) {
  return verifyLab({ lab: await lab(), sandbox: new FakeSandbox(w), namespace: SANDBOX });
}

function failed(checks: Array<{ status: string; label: string }>): string[] {
  return checks.filter((c) => c.status !== 'pass').map((c) => c.label);
}

// ------------------------------------------------- execution, not intention

describe('LINUX-018 grades that the job ran, not that it was scheduled', () => {
  it('passes a host where the scheduler ran the rollup', async () => {
    const result = await verify(world());

    expect(failed(result.checks)).toEqual([]);
    expect(result.passed).toBe(true);
  });

  it('fails the seeded state, where a valid-looking entry has never fired', async () => {
    const result = await verify(world({ crontab: SEEDED_ENTRY, toolMode: '644', status: null, cronLog: '' }));

    expect(result.passed).toBe(false);
    // The premise of the whole lab: cron is up and an entry exists, and
    // nothing has happened.
    expect(failed(result.checks)).not.toContain('The scheduler is still running');
    expect(failed(result.checks)).toContain('The rollup produced a result');
  });

  it('fails a correct crontab whose job has never executed', async () => {
    // The single most important case. Everything about the configuration is
    // right; no run has happened. A lab that graded the crontab alone would
    // pass this.
    const result = await verify(world({ status: null, cronLog: '' }));

    expect(result.passed).toBe(false);
    expect(failed(result.checks)).toEqual([
      'The rollup produced a result',
      'The scheduler ran the rollup, rather than a person running it by hand',
      'The rollup read the whole event log',
      'That result is from a recent run rather than a leftover',
      "The job's own output is landing in the log",
    ]);
  });

  it('fails a rollup the student produced by running the tool by hand', async () => {
    /*
     * The anti-false-positive case, confirmed end to end against the real
     * sandbox: the tool records RUNBY=shell when a person starts it. Output
     * exists, the log line exists, the file is fresh — and it still fails,
     * because none of that was the scheduler's doing.
     */
    const result = await verify(
      world({
        crontab: CORRECT_ENTRY,
        status: 'ROLLUP=OK\nRUNBY=shell\nRECORDS=1440\nAT=2026-08-25T14:33:55+00:00\n',
      }),
    );

    expect(result.passed).toBe(false);
    expect(failed(result.checks)).toEqual([
      'The scheduler ran the rollup, rather than a person running it by hand',
    ]);
  });

  it('fails a stale result from a run that has since stopped happening', async () => {
    const result = await verify(world({ fresh: false }));

    expect(result.passed).toBe(false);
    expect(failed(result.checks)).toEqual([
      'That result is from a recent run rather than a leftover',
    ]);
  });
});

// --------------------------------------------------------- the three faults

describe('LINUX-018 distinguishes the three faults it seeds', () => {
  it('fails a schedule that fires far less often than the window requires', async () => {
    const result = await verify(world({ crontab: `0 3 * * * ${TOOL} >> ${CRON_LOG} 2>&1\n` }));

    expect(result.passed).toBe(false);
    expect(failed(result.checks)).toEqual([
      'The entry fires as often as the incident window requires',
    ]);
  });

  it('fails a bare command name, which cron cannot resolve on its short PATH', async () => {
    // Verified in the sandbox: cron logs `/bin/sh: 1: jtt-rollup: not found`.
    const result = await verify(
      world({ crontab: `* * * * * jtt-rollup >> ${CRON_LOG} 2>&1\n` }),
    );

    expect(result.passed).toBe(false);
    expect(failed(result.checks)).toEqual(['The entry names the tool by its absolute path']);
  });

  it('fails a tool the scheduler cannot execute', async () => {
    // Verified in the sandbox: cron logs `Permission denied` for mode 0644.
    const result = await verify(world({ toolMode: '644' }));

    expect(result.passed).toBe(false);
    expect(failed(result.checks)).toEqual(['The rollup tool can actually be executed']);
  });

  it('fails an entry that discards its output, so a failure would be silent', async () => {
    const result = await verify(world({ crontab: `* * * * * ${TOOL}\n` }));

    expect(result.passed).toBe(false);
    expect(failed(result.checks)).toEqual([
      "The job's output is sent somewhere a person can read it",
    ]);
  });

  it('fails a host where the scheduler itself has stopped', async () => {
    const result = await verify(world({ cronRunning: false }));

    expect(result.passed).toBe(false);
    expect(failed(result.checks)).toEqual(['The scheduler is still running']);
  });

  it('fails a rollup that read the wrong input', async () => {
    const result = await verify(
      world({ status: 'ROLLUP=OK\nRUNBY=cron\nRECORDS=0\nAT=2026-08-25T14:35:02+00:00\n' }),
    );

    expect(result.passed).toBe(false);
    expect(failed(result.checks)).toEqual(['The rollup read the whole event log']);
  });

  it('fails an untouched sandbox with every check reported', async () => {
    const result = await verify({});

    expect(result.passed).toBe(false);
    expect(result.checks).toHaveLength((await lab()).requirements.length);
    expect(result.checks.every((c) => c.status !== 'skipped')).toBe(true);
  });
});

// ------------------------------------------------------------- lab hygiene

describe('LINUX-018 grades state, and never the route taken to it', () => {
  it('never runs the student job itself', async () => {
    // The verifier must not be the thing that causes execution — the whole
    // lab is about whether the scheduler does.
    const definition = await lab();
    for (const requirement of [...definition.requirements, ...definition.setup.verify]) {
      expect(requirement.type).not.toBe('script_runs');
    }
  });

  it('names only allow-listed read-only commands with fixed arguments', async () => {
    const definition = await lab();
    const permitted = new Map<string, string[][]>([
      ['cat', [['/var/spool/cron/crontabs/student']]],
      ['find', [[STATUS, '-mmin', '-3']]],
    ]);

    for (const requirement of [...definition.requirements, ...definition.setup.verify]) {
      if (requirement.type !== 'command_exit_code' && requirement.type !== 'command_output') continue;
      const allowed = permitted.get(requirement.command);
      expect(allowed, `unexpected command '${requirement.command}'`).toBeDefined();
      expect(allowed).toContainEqual([...requirement.args]);
    }
  });

  it('reads the user crontab as root, because it is 0600 in a spool the account cannot list', async () => {
    const definition = await lab();
    const reads = definition.requirements.filter(
      (r) => r.type === 'command_output' && r.command === 'cat',
    );
    expect(reads.length).toBeGreaterThan(0);
    for (const r of reads) expect('as_user' in r ? r.as_user : undefined).toBe('root');
  });

  it('bounds the setup budget rather than sleeping for a scheduler run', async () => {
    // Setup asserts the seeded job has never run, which needs no waiting. The
    // budget covers a slow container start, and nothing in the verifier sleeps.
    const definition = await lab();
    expect(definition.setup.verify_timeout_seconds).toBeLessThanOrEqual(300);
    expect(definition.setup.verify_timeout_seconds).toBeGreaterThanOrEqual(60);
  });

  it('never names the fix in a failure detail', async () => {
    const result = await verify(world({ crontab: SEEDED_ENTRY, toolMode: '644', status: null, cronLog: '' }));

    for (const check of result.checks.filter((c) => c.status !== 'pass')) {
      expect(check.detail ?? '', check.label).not.toMatch(
        /\*\s\*\s\*\s\*\s\*|chmod|RUNBY|2>&1/,
      );
    }
  });

  it('claims the certification domain the competency list actually names', async () => {
    // "Manage or schedule jobs for executing commands" — Operations Deployment,
    // read from the published LFCS competency list on 2026-08-25.
    const certification = (await lab()).certification;
    expect(certification[0]?.certification).toBe('LFCS');
    expect(certification[0]?.relevant).toBe(true);
    expect(certification[0]?.domains).toEqual(['operations-deployment']);
  });
});
