/**
 * NET-023 — verification for the container DNS lab.
 *
 * The lesson NET-023 teaches is a property of the daemon, not of a file the
 * student wrote: a container on a user-defined bridge network resolves through
 * the daemon's embedded DNS at `127.0.0.11`, and a container on the default
 * bridge does not. So the check that carries the lab is the one that reads
 * `/etc/resolv.conf` *inside* each container through the archive endpoint. That
 * is the platform observing the embedded resolver, and no worksheet value can
 * stand in for it.
 *
 * The sections below are the three claims that has to hold:
 *
 *   1. the seeded incident fails — both containers on the default bridge, both
 *      resolvers pointing at the daemon host, nothing created;
 *   2. the repair passes — a user-defined bridge network, both containers
 *      attached to it, both resolvers rewritten;
 *   3. a partial or forged repair fails, one way per test. The one that matters
 *      most is the forged worksheet: writing `127.0.0.11` into `diagnosis.txt`
 *      without moving the containers must not pass, because the resolver is
 *      read from the containers themselves.
 *
 * The behaviour these fixtures model was measured on Docker Engine 28.4.0 on
 * 2026-09-16; the lab's own header records the measurements.
 */
import { beforeAll, describe, expect, it } from 'vitest';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  InMemoryWorkspace,
  loadLabDefinition,
  type LoadedLabDefinition,
} from '@jumptotech/lab-orchestrator';
import { FakeDockerDaemon, containerSpec } from '@jumptotech/lab-orchestrator/testing';
import { verifyLab } from '../src/index.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const LABS_DIR = path.resolve(here, '../../../labs');
const NET_023 = path.join(LABS_DIR, 'networking', 'net-023-container-dns', 'lab.yaml');

const SANDBOX = 'lab-00000000000a';
const SESSION = 'sess-000000000000000a';

let lab: LoadedLabDefinition;
beforeAll(async () => {
  lab = await loadLabDefinition(NET_023);
});

function failures(checks: Array<{ status: string; label: string; detail?: string }>) {
  return checks.filter((c) => c.status !== 'pass');
}

/**
 * `/etc/resolv.conf` as the daemon writes it, in each of the two cases.
 *
 * Both are real files, copied from a container on Docker Engine 28.4.0 with
 * the addresses generalised. The distinguishing line is the nameserver, which
 * is the whole point of the lab.
 */
const RESOLV_DEFAULT_BRIDGE = [
  '# Generated by Docker Engine.',
  '# This file can be edited; Docker Engine will not make further changes once it',
  '# has been modified.',
  '',
  'nameserver 192.168.65.7',
  '',
  "# Based on host file: '/etc/resolv.conf' (legacy)",
  '# Overrides: []',
  '',
].join('\n');

const RESOLV_EMBEDDED_DNS = [
  '# Generated by Docker Engine.',
  '# This file can be edited; Docker Engine will not make further changes once it',
  '# has been modified.',
  '',
  'nameserver 127.0.0.11',
  'options ndots:0',
  '',
  "# Based on host file: '/etc/resolv.conf' (internal resolver)",
  '# ExtServers: [host(192.168.65.7)]',
  '# Overrides: []',
  '',
].join('\n');

const SOLVED_DIAGNOSIS = [
  'name_lookup_before: not_resolved',
  'network_before: bridge',
  'resolver_after: 127.0.0.11',
  'why_the_lookup_failed: the default bridge does not serve container names',
  '',
].join('\n');

const SOLVED_SCOPE = [
  'The third container is on ledger-canary-net, so its name is known to that',
  'network and not to the daemon as a whole.',
  'docker network connect --alias adds a second network-scoped name.',
  '',
].join('\n');

interface WorldOptions {
  /** Create the user-defined network the task asks for. */
  ledgerNet?: boolean;
  /** Attach these containers to it. */
  attached?: string[];
  /** Per-container /etc/resolv.conf. Defaults to the default-bridge one. */
  resolv?: Record<string, string>;
  /** The image ledger-api is running. */
  apiImage?: string;
  /** Leave the canary on its own network. */
  canaryNetwork?: string | null;
  diagnosis?: string;
  scope?: string;
}

/**
 * The session's daemon, in whatever state the test is describing.
 *
 * The seeded baseline is the default: three containers, the canary on its own
 * network, the other two on the default bridge with the host's resolver, and
 * blank worksheets.
 */
function world(options: WorldOptions = {}) {
  const docker = new FakeDockerDaemon({ images: ['nginx:1.27-alpine', 'alpine:3.20'] });
  docker.createNetwork({ name: 'ledger-canary-net', driver: 'bridge' });
  if (options.ledgerNet !== false) {
    // Present by default only when something is attached to it; a test that
    // wants the seeded baseline passes `ledgerNet: false`.
  }
  if (options.ledgerNet) docker.createNetwork({ name: 'ledger-net', driver: 'bridge' });

  docker.addContainer(
    containerSpec({ name: 'ledger-api', image: options.apiImage ?? 'nginx:1.27-alpine' }),
  );
  docker.addContainer(
    containerSpec({ name: 'ledger-worker', image: 'alpine:3.20', command: ['sh', '-c', 'exec sleep 3600'] }),
  );
  if (options.canaryNetwork !== null) {
    docker.addContainer(
      containerSpec({
        name: 'ledger-api-canary',
        image: 'nginx:1.27-alpine',
        network: options.canaryNetwork ?? 'ledger-canary-net',
      }),
    );
  } else {
    docker.addContainer(containerSpec({ name: 'ledger-api-canary', image: 'nginx:1.27-alpine' }));
  }

  for (const name of options.attached ?? []) docker.attachNetwork(name, 'ledger-net');

  for (const name of ['ledger-api', 'ledger-worker', 'ledger-api-canary']) {
    docker.putFile(name, '/etc/resolv.conf', options.resolv?.[name] ?? RESOLV_DEFAULT_BRIDGE);
  }

  const port = new InMemoryWorkspace();
  port.write(SESSION, 'diagnosis.txt', options.diagnosis ?? 'name_lookup_before: ____\n');
  port.write(SESSION, 'scope.txt', options.scope ?? '# NET-023 — the scope of a container name\n');

  return { docker, workspace: { port, sessionId: SESSION } };
}

/** Everything the lab asks for, done honestly. */
function solved(overrides: WorldOptions = {}) {
  return world({
    ledgerNet: true,
    attached: ['ledger-api', 'ledger-worker'],
    resolv: {
      'ledger-api': RESOLV_EMBEDDED_DNS,
      'ledger-worker': RESOLV_EMBEDDED_DNS,
    },
    diagnosis: SOLVED_DIAGNOSIS,
    scope: SOLVED_SCOPE,
    ...overrides,
  });
}

const verify = (state: ReturnType<typeof world>) =>
  verifyLab({ lab, namespace: SANDBOX, docker: state.docker, workspace: state.workspace });

// --------------------------------------------------------- 1. the incident

describe('NET-023 before the work', () => {
  it('fails on the seeded incident', async () => {
    const result = await verify(world());

    expect(result.passed).toBe(false);
    expect(result.summary).toBe('LAB NOT COMPLETE');
    // The network does not exist, neither container is attached to it, and
    // neither resolver is the embedded one.
    expect(failures(result.checks).length).toBeGreaterThanOrEqual(5);
  });

  it('fails on an empty daemon rather than erroring', async () => {
    const result = await verifyLab({
      lab,
      namespace: SANDBOX,
      docker: new FakeDockerDaemon(),
      workspace: { port: new InMemoryWorkspace(), sessionId: SESSION },
    });

    expect(result.passed).toBe(false);
    expect(failures(result.checks).length).toBeGreaterThan(0);
  });

  it('never hands over the resolver address in a check label or detail', async () => {
    const result = await verify(world());
    const reported = JSON.stringify(result.checks);

    // `docker_container_file_content` reports structural facts only, so the
    // value it grades must not appear anywhere in what the student is shown.
    expect(reported).not.toContain('127.0.0.11');
    expect(reported).not.toContain('--alias');
  });
});

// ----------------------------------------------------------- 2. the repair

describe('NET-023 after the work', () => {
  it('passes when both containers are on a user-defined network with the embedded resolver', async () => {
    const result = await verify(solved());

    expect(failures(result.checks)).toEqual([]);
    expect(result.passed).toBe(true);
    expect(result.summary).toBe('LAB PASSED');
  });

  it('accepts a container that is on the default bridge as well as the new network', async () => {
    // `docker network connect` adds a network; it does not remove the one the
    // container was created on. The lab grades attachment, not exclusivity.
    const state = solved();
    expect(
      state.docker.containers.get('ledger-worker')?.spec.network ?? 'bridge',
    ).toBe('bridge');

    const result = await verify(state);
    expect(result.passed).toBe(true);
  });
});

// ------------------------------------------- 3. partial and forged repairs

describe('NET-023 rejects a repair that did not happen', () => {
  it('fails when the worksheet claims the embedded resolver but the containers still have the host one', async () => {
    // The forgery this lab's design exists to defeat: the resolver is read
    // from the containers, so writing the right answer down is not enough.
    const result = await verify(
      solved({ resolv: { 'ledger-api': RESOLV_DEFAULT_BRIDGE, 'ledger-worker': RESOLV_DEFAULT_BRIDGE } }),
    );

    expect(result.passed).toBe(false);
    expect(failures(result.checks)).toHaveLength(2);
  });

  it('fails when the network exists but nothing was attached to it', async () => {
    const result = await verify(
      world({ ledgerNet: true, diagnosis: SOLVED_DIAGNOSIS, scope: SOLVED_SCOPE }),
    );
    expect(result.passed).toBe(false);
  });

  it('fails when only one of the two containers was moved', async () => {
    const result = await verify(
      solved({
        attached: ['ledger-worker'],
        resolv: { 'ledger-worker': RESOLV_EMBEDDED_DNS, 'ledger-api': RESOLV_DEFAULT_BRIDGE },
      }),
    );
    expect(result.passed).toBe(false);
  });

  it('fails when the network was never created', async () => {
    const result = await verify(
      world({ diagnosis: SOLVED_DIAGNOSIS, scope: SOLVED_SCOPE }),
    );
    expect(result.passed).toBe(false);
  });

  it('fails when ledger-api was recreated on a different image', async () => {
    const result = await verify(solved({ apiImage: 'alpine:3.20' }));
    expect(result.passed).toBe(false);
  });

  it('fails when the third container was taken off its own network', async () => {
    const result = await verify(solved({ canaryNetwork: null }));
    expect(result.passed).toBe(false);
  });

  it.each([
    ['the wrong network is named as the one the API was on', 'network_before: ledger-net'],
    ['the lookup is claimed to have worked before', 'name_lookup_before: resolved'],
    ['the resolver is left unanswered', 'resolver_after: ____'],
  ])('fails when %s', async (_name, line) => {
    const diagnosis = SOLVED_DIAGNOSIS.split('\n')
      .filter((l) => !l.startsWith(line.split(':')[0] ?? ''))
      .concat(line, '')
      .join('\n');
    const result = await verify(solved({ diagnosis }));
    expect(result.passed).toBe(false);
  });

  it('fails when scope.txt names neither the network nor the option', async () => {
    const result = await verify(
      solved({ scope: 'Container DNS is per-network. You can add extra names.\n' }),
    );
    expect(result.passed).toBe(false);
  });
});
